### ISSUE TITLE
Can't install wallpapper

### ISSUE THREAD

**Issue by Pastorl5** [mczachurski/homebrew-wallpapper#2]
Got the following error code: 

error: terminated(72): xcrun --sdk macosx --find xctest output:

**Comment by amsoell** [comment]
I had the same problem until, per the "Troubleshooting" section of the README, I ran this:

```bash
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

**Comment by steven-t-h** [comment]
@Pastorl5 @amsoell I had the same issue and the command fixed it. You should also run
 `sudo xcodebuild -license accept`
if you haven't opened up Xcode yet (fresh install).
